### ISSUE TITLE
Friends list issue when using with PinDMS

### ISSUE THREAD

**Issue by jpopie** [DaBluLite/Cyan#5]
![image_2023-07-19_182821635](https://github.com/DaBluLite/Cyan/assets/50598293/a8374ecd-b16b-46f2-9742-98c2e846d308)

Only happened after most recent discord update. unable to see names and it looks like its compacted, no settings in PinDMS to change this also.

**Comment by DaBluLite** [comment]
That would be a result from a recent cyan update, I will look into fixing the issue. Thanks for letting me know.

**Comment by DaBluLite** [comment]
Cyan version 16.8.2 resolves the issue

**Comment by JLanderman** [comment]
This issue seems to have appeared again. I've been using this theme on both Mac and Windows and this suddenly appeared out of nowhere on both of them. I threw the following code into a custom theme I made and got the names to reappear, though I don't know if it is how you'd want to do things.

`#app-mount > div.appAsidePanelWrapper_bd26cc > div.notAppAsidePanel_bd26cc > div.app_bd26cc > div > div.layers_d4b6c5.layers_a01fb1 > div > div > div > div > div.sidebar_a4d4d9 > nav > div.scroller_c47fa9.thin_eed6a8.scrollerBase_eed6a8.fade_eed6a8 > ul > li > div > a > div > div.content_ec8679 {
    display: flex !important;
    flex-direction: row !important;
    align-items: center !important;
    justify-content: flex-start !important;
}`
